Sndfile: error message update
Updated ValueError message for incompatible selections so the results are more descriptive, reporting back the params selected. An failed example for 'aiff' at 'pcm24' is listed below. (PSL doesn't support 'aiff', 'pcm24', as it is regarded as a compression type.)

ValueError: The combination (type = aiff|encoding = pcm24|endianness = file) you requested is not supported. You can use available_formats and available_encodings functions to query which formats and encodings are available.
Signed-off-by: Joseph Anderson <josephlloydanderson@mac.com>